//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class AccountTransfers : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Account ffromAccount;
        public Account fromAccount
        {
            get { return ffromAccount; }
            set { SetPropertyValue<Account>(nameof(fromAccount), ref ffromAccount, value); }
        }
        Account ftoAccount;
        public Account toAccount
        {
            get { return ftoAccount; }
            set { SetPropertyValue<Account>(nameof(toAccount), ref ftoAccount, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        bool fTransferd;
        public bool Transferd
        {
            get { return fTransferd; }
            set { SetPropertyValue<bool>(nameof(Transferd), ref fTransferd, value); }
        }
    }

}
