//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [Persistent(@"Stay")]
    public partial class Admission : XPBaseObject
    {
        int fadmissionID;
        [Key(true)]
        [Persistent(@"StayID")]
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public int admissionID
        {
            get { return fadmissionID; }
            set { SetPropertyValue<int>(nameof(admissionID), ref fadmissionID, value); }
        }
        Patient fPatient;
        [Association(@"StayReferencesPatient")]
        [DevExpress.Persistent.Base.DataSourceCriteria(" InStay = false"),
]
        public Patient Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<Patient>(nameof(Patient), ref fPatient, value); }
        }
        Room fRoom;
        [DevExpress.Persistent.Base.DataSourceCriteria(" Status='@This.Status' ")]
        public Room Room
        {
            get { return fRoom; }
            set { SetPropertyValue<Room>(nameof(Room), ref fRoom, value); }
        }
        bed fbed;
        [DevExpress.Persistent.Base.DataSourceCriteria("room == '@This.Room' AND isAvailable  ")
]
        public bed bed
        {
            get { return fbed; }
            set { SetPropertyValue<bed>(nameof(bed), ref fbed, value); }
        }
        Employee fdoctor;
        [DevExpress.Persistent.Base.DataSourceCriteria(" section= 6")]
        public Employee doctor
        {
            get { return fdoctor; }
            set { SetPropertyValue<Employee>(nameof(doctor), ref fdoctor, value); }
        }
        string ffinalDiagnosis;
        [Size(SizeAttribute.Unlimited)]
        public string finalDiagnosis
        {
            get { return ffinalDiagnosis; }
            set { SetPropertyValue<string>(nameof(finalDiagnosis), ref ffinalDiagnosis, value); }
        }
        string ffirstDiagnosis;
        [Size(SizeAttribute.Unlimited)]
        public string firstDiagnosis
        {
            get { return ffirstDiagnosis; }
            set { SetPropertyValue<string>(nameof(firstDiagnosis), ref ffirstDiagnosis, value); }
        }
        DateTime fStayStart;
        public DateTime StayStart
        {
            get { return fStayStart; }
            set { SetPropertyValue<DateTime>(nameof(StayStart), ref fStayStart, value); }
        }
        DateTime fStayEnd;
        public DateTime StayEnd
        {
            get { return fStayEnd; }
            set { SetPropertyValue<DateTime>(nameof(StayEnd), ref fStayEnd, value); }
        }
        [PersistentAlias("[StayStart]")]
        public DateTime date
        {
            get { return (DateTime)(EvaluateAlias(nameof(date))); }
        }
        ReceptionDesk freception;
        [Association(@"AdmissionReferencesReceptionDesk")]
        public ReceptionDesk reception
        {
            get { return freception; }
            set { SetPropertyValue<ReceptionDesk>(nameof(reception), ref freception, value); }
        }
        bool ftransferFlag;
        public bool transferFlag
        {
            get { return ftransferFlag; }
            set { SetPropertyValue<bool>(nameof(transferFlag), ref ftransferFlag, value); }
        }
        bool ftransferDayCount;
        public bool transferDayCount
        {
            get { return ftransferDayCount; }
            set { SetPropertyValue<bool>(nameof(transferDayCount), ref ftransferDayCount, value); }
        }
        bool fIsDischarged;
        [ColumnDefaultValue(false)]
        [DevExpress.Persistent.Base.VisibleInDetailView(false)]
        public bool IsDischarged
        {
            get { return fIsDischarged; }
            set { SetPropertyValue<bool>(nameof(IsDischarged), ref fIsDischarged, value); }
        }
        [PersistentAlias("Iif([StayMedicications][[Package] = null].Sum([total]) Is Null Or [StayMedicications][].Sum([total]) Is Null, 0.0m, [StayMedicications][[Package] = null].Sum([total]))")]
        public decimal medicationSum
        {
            get { return (decimal)(EvaluateAlias(nameof(medicationSum))); }
        }
        [PersistentAlias("Iif([StockDetailsCollection][[Package] = null].Sum([total]) Is Null Or [StockDetailsCollection][].Sum([total]) Is Null, 0.0m, [StockDetailsCollection][[Package] = null].Sum([total]))")]
        public decimal suppliesSum
        {
            get { return (decimal)(EvaluateAlias(nameof(suppliesSum))); }
        }
        [PersistentAlias("Iif([ServiceDetailsCollection][[Package] = null].Sum([price]) Is Null Or [ServiceDetailsCollection][].Sum([price]) Is Null, 0.0m, [ServiceDetailsCollection][[Package] = null].Sum([price]))")]
        public decimal servicesSum
        {
            get { return (decimal)(EvaluateAlias(nameof(servicesSum))); }
        }
        [PersistentAlias("Iif([CompanionDetailsCollection][[Package] = null].Sum([price]) Is Null Or [CompanionDetailsCollection][].Sum([price]) Is Null, 0.0m, [CompanionDetailsCollection][[Package] = null].Sum([price]))")]
        public decimal companionSum
        {
            get { return (decimal)(EvaluateAlias(nameof(companionSum))); }
        }
        [PersistentAlias("Iif([EndscopeDetailsCollection][[Package] = null].Sum([price]) Is Null Or [EndscopeDetailsCollection][].Sum([price]) Is Null, 0.0m, [EndscopeDetailsCollection][[Package] = null].Sum([price]))")]
        public decimal endscopesSum
        {
            get { return (decimal)(EvaluateAlias(nameof(endscopesSum))); }
        }
        [PersistentAlias("Iif([TestDetailsCollection][[Package] = null].Sum([price]) Is Null Or [TestDetailsCollection][].Sum([price]) Is Null, 0.0m, [TestDetailsCollection][[Package] = null].Sum([price]))")]
        public decimal testsSum
        {
            get { return (decimal)(EvaluateAlias(nameof(testsSum))); }
        }
        [PersistentAlias("Iif([XraysDetailsCollection][[Package] = null].Sum([price]) Is Null Or [XraysDetailsCollection][].Sum([price]) Is Null, 0.0m, [XraysDetailsCollection][[Package] = null].Sum([price]))")]
        public decimal xraysSum
        {
            get { return (decimal)(EvaluateAlias(nameof(xraysSum))); }
        }
        double ftotalDays;
        public double totalDays
        {
            get { return ftotalDays; }
            set { SetPropertyValue<double>(nameof(totalDays), ref ftotalDays, value); }
        }
        [PersistentAlias("[stayTotalSum]")]
        public decimal amount
        {
            get { return (decimal)(EvaluateAlias(nameof(amount))); }
        }
        bool fignoreFirstDay;
        public bool ignoreFirstDay
        {
            get { return fignoreFirstDay; }
            set { SetPropertyValue<bool>(nameof(ignoreFirstDay), ref fignoreFirstDay, value); }
        }
        decimal froomStaySum;
        public decimal roomStaySum
        {
            get { return froomStaySum; }
            set { SetPropertyValue<decimal>(nameof(roomStaySum), ref froomStaySum, value); }
        }
        decimal fmedicalCareSum;
        public decimal medicalCareSum
        {
            get { return fmedicalCareSum; }
            set { SetPropertyValue<decimal>(nameof(medicalCareSum), ref fmedicalCareSum, value); }
        }
        decimal fMedicalSupervisionSum;
        public decimal MedicalSupervisionSum
        {
            get { return fMedicalSupervisionSum; }
            set { SetPropertyValue<decimal>(nameof(MedicalSupervisionSum), ref fMedicalSupervisionSum, value); }
        }
        [PersistentAlias("[companionSum] + [servicesSum] + [suppliesSum] + [endscopesSum] + [testsSum] + [xraysSum] + [MedicalSupervisionSum] + [medicalCareSum] + [roomStaySum] + [ConsolationSum] + [OutMedcationSum]")]
        public decimal stayTotalSum
        {
            get { return (decimal)(EvaluateAlias(nameof(stayTotalSum))); }
        }
        decimal froomStayCost;
        public decimal roomStayCost
        {
            get { return froomStayCost; }
            set { SetPropertyValue<decimal>(nameof(roomStayCost), ref froomStayCost, value); }
        }
        decimal froomCareCost;
        public decimal roomCareCost
        {
            get { return froomCareCost; }
            set { SetPropertyValue<decimal>(nameof(roomCareCost), ref froomCareCost, value); }
        }
        decimal froomSupervisionCost;
        public decimal roomSupervisionCost
        {
            get { return froomSupervisionCost; }
            set { SetPropertyValue<decimal>(nameof(roomSupervisionCost), ref froomSupervisionCost, value); }
        }
        [PersistentAlias("Iif([ConsultantDetailsCollection][[Package] = null].Sum([Price]) Is Null Or [ConsultantDetailsCollection][].Sum([Price]) Is Null, 0.0m, [ConsultantDetailsCollection][[Package] = null].Sum([Price]))")]
        public decimal ConsolationSum
        {
            get { return (decimal)(EvaluateAlias(nameof(ConsolationSum))); }
        }
        [PersistentAlias("Iif([OutMedications][].Sum([amount]) Is Null, 0.0m, [OutMedications][].Sum([amount]))")]
        public decimal OutMedcationSum
        {
            get { return (decimal)(EvaluateAlias(nameof(OutMedcationSum))); }
        }
        Department fDepartment;
        public Department Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<Department>(nameof(Department), ref fDepartment, value); }
        }
        bool fhalfDayAtStart;
        public bool halfDayAtStart
        {
            get { return fhalfDayAtStart; }
            set { SetPropertyValue<bool>(nameof(halfDayAtStart), ref fhalfDayAtStart, value); }
        }
        bool fHalfDayAtEnd;
        public bool HalfDayAtEnd
        {
            get { return fHalfDayAtEnd; }
            set { SetPropertyValue<bool>(nameof(HalfDayAtEnd), ref fHalfDayAtEnd, value); }
        }
        int fdayOffset;
        public int dayOffset
        {
            get { return fdayOffset; }
            set { SetPropertyValue<int>(nameof(dayOffset), ref fdayOffset, value); }
        }
        [Association(@"SupervisionDetailsReferencesAdmission")]
        public XPCollection<SupervisionDetails> SupervisionDetailsCollection { get { return GetCollection<SupervisionDetails>(nameof(SupervisionDetailsCollection)); } }
        [Association(@"TestDetailsReferencesAdmission")]
        public XPCollection<TestDetails> TestDetailsCollection { get { return GetCollection<TestDetails>(nameof(TestDetailsCollection)); } }
        [Association(@"ConsultantDetailsReferencesAdmission")]
        public XPCollection<ConsultantDetails> ConsultantDetailsCollection { get { return GetCollection<ConsultantDetails>(nameof(ConsultantDetailsCollection)); } }
        [Association(@"CompanionDetailsReferencesAdmission")]
        public XPCollection<CompanionDetails> CompanionDetailsCollection { get { return GetCollection<CompanionDetails>(nameof(CompanionDetailsCollection)); } }
        [Association(@"XraysDetailsReferencesAdmission")]
        public XPCollection<XraysDetails> XraysDetailsCollection { get { return GetCollection<XraysDetails>(nameof(XraysDetailsCollection)); } }
        [Association(@"EndscopeDetailsReferencesAdmission")]
        public XPCollection<EndscopeDetails> EndscopeDetailsCollection { get { return GetCollection<EndscopeDetails>(nameof(EndscopeDetailsCollection)); } }
        [Association(@"ServiceDetailsReferencesAdmission")]
        public XPCollection<ServiceDetails> ServiceDetailsCollection { get { return GetCollection<ServiceDetails>(nameof(ServiceDetailsCollection)); } }
        [Association(@"StayMedicationsReferencesAdmission")]
        public XPCollection<StayMedications> StayMedicications { get { return GetCollection<StayMedications>(nameof(StayMedicications)); } }
        [Association(@"StaySuppliesReferencesAdmission")]
        public XPCollection<StaySupplies> StockDetailsCollection { get { return GetCollection<StaySupplies>(nameof(StockDetailsCollection)); } }
        [Association(@"ProductRefundReferencesAdmission")]
        public XPCollection<ProductRefund> ProductRefunds { get { return GetCollection<ProductRefund>(nameof(ProductRefunds)); } }
        [Association(@"OutMedicationReferencesAdmission")]
        public XPCollection<OutMedication> OutMedications { get { return GetCollection<OutMedication>(nameof(OutMedications)); } }
    }

}
