//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Appointment : DevExpress.Persistent.BaseImpl.Event
    {
        int fid;
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Patient fPatient;
        [Association(@"AppointmentReferencesPatient")]
        public Patient Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<Patient>(nameof(Patient), ref fPatient, value); }
        }
        Clinc fclinc;
        public Clinc clinc
        {
            get { return fclinc; }
            set { SetPropertyValue<Clinc>(nameof(clinc), ref fclinc, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        [PersistentAlias("Iif([ServiceDetailsCollection][].Sum([price]) Is Null, [amount], [ServiceDetailsCollection][].Sum([price]) + [amount])")]
        public decimal total
        {
            get { return (decimal)(EvaluateAlias(nameof(total))); }
        }
        Employee fDoctor;
        [Association(@"AppointmentReferencesEmployee")]
        public Employee Doctor
        {
            get { return fDoctor; }
            set { SetPropertyValue<Employee>(nameof(Doctor), ref fDoctor, value); }
        }
        [Association(@"ServiceDetailsReferencesAppointment"), Aggregated]
        public XPCollection<ServiceDetails> ServiceDetailsCollection { get { return GetCollection<ServiceDetails>(nameof(ServiceDetailsCollection)); } }
        [Association(@"ClinicServiceDetailReferencesAppointment"), Aggregated]
        public XPCollection<ClinicServiceDetail> ClinicServiceDetails { get { return GetCollection<ClinicServiceDetail>(nameof(ClinicServiceDetails)); } }
    }

}
