//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class bed : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fnumber;
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public string number
        {
            get { return fnumber; }
            set { SetPropertyValue<string>(nameof(number), ref fnumber, value); }
        }
        Room froom;
        [Association(@"bedReferencesRoom")]
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public Room room
        {
            get { return froom; }
            set { SetPropertyValue<Room>(nameof(room), ref froom, value); }
        }
        bool fisAvailable;
        public bool isAvailable
        {
            get { return fisAvailable; }
            set { SetPropertyValue<bool>(nameof(isAvailable), ref fisAvailable, value); }
        }
    }

}
