//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.ExpressApp.DefaultListViewOptions(DevExpress.ExpressApp.MasterDetailMode.ListViewOnly, true, DevExpress.ExpressApp.NewItemRowPosition.Bottom)]
    public partial class BonusDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        string fnote;
        [Size(SizeAttribute.Unlimited)]
        public string note
        {
            get { return fnote; }
            set { SetPropertyValue<string>(nameof(note), ref fnote, value); }
        }
        Employee femployee;
        [Association(@"BonusDetailsReferencesEmployee")]
        public Employee employee
        {
            get { return femployee; }
            set { SetPropertyValue<Employee>(nameof(employee), ref femployee, value); }
        }
        SalaryDeduction fSalaryDeduction;
        [Association(@"BonusDetailsReferencesSalaryDeduction")]
        public SalaryDeduction SalaryDeduction
        {
            get { return fSalaryDeduction; }
            set { SetPropertyValue<SalaryDeduction>(nameof(SalaryDeduction), ref fSalaryDeduction, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
    }

}
