//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Clinc : XPBaseObject
    {
        int fid;
        [Key]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fName;
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fdescription;
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        Employee finCharge;
        [DevExpress.Persistent.Base.DataSourceCriteria(" section= 6"), DevExpress.Persistent.Validation.RuleRequiredField,]
        public Employee inCharge
        {
            get { return finCharge; }
            set { SetPropertyValue<Employee>(nameof(inCharge), ref finCharge, value); }
        }
        string fClinicNumber;
        public string ClinicNumber
        {
            get { return fClinicNumber; }
            set { SetPropertyValue<string>(nameof(ClinicNumber), ref fClinicNumber, value); }
        }
        string fClinicLetter;
        public string ClinicLetter
        {
            get { return fClinicLetter; }
            set { SetPropertyValue<string>(nameof(ClinicLetter), ref fClinicLetter, value); }
        }
        decimal fExaminationPrice;
        public decimal ExaminationPrice
        {
            get { return fExaminationPrice; }
            set { SetPropertyValue<decimal>(nameof(ExaminationPrice), ref fExaminationPrice, value); }
        }
    }

}
