//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ClinicServiceDetail : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Service fClinicService;
        [DevExpress.Persistent.Base.DataSourceCriteria(" Departmet= '@This.Appointment.clinc.Department'")]
        public Service ClinicService
        {
            get { return fClinicService; }
            set { SetPropertyValue<Service>(nameof(ClinicService), ref fClinicService, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Appointment fAppointment;
        [Association(@"ClinicServiceDetailReferencesAppointment")]
        public Appointment Appointment
        {
            get { return fAppointment; }
            set { SetPropertyValue<Appointment>(nameof(Appointment), ref fAppointment, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
    }

}
