//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ClinicServiceDetail : XPObject
    {
        int fID;
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        ClinicService fClinicService;
        public ClinicService ClinicService
        {
            get { return fClinicService; }
            set { SetPropertyValue<ClinicService>(nameof(ClinicService), ref fClinicService, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Appointment fAppointment;
        [Association(@"ClinicServiceDetailReferencesAppointment")]
        public Appointment Appointment
        {
            get { return fAppointment; }
            set { SetPropertyValue<Appointment>(nameof(Appointment), ref fAppointment, value); }
        }
    }

}
