//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.ExpressApp.DefaultListViewOptions(DevExpress.ExpressApp.MasterDetailMode.ListViewOnly, true, DevExpress.ExpressApp.NewItemRowPosition.Bottom)]
    public partial class CompensationDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        DateTime fdate;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy}"), DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy")
]
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        Employee femployee;
        [Association(@"CompensationReferencesEmployee")]
        public Employee employee
        {
            get { return femployee; }
            set { SetPropertyValue<Employee>(nameof(employee), ref femployee, value); }
        }
        [PersistentAlias("Iif([employee.BonusDetailsCollection][].Sum([amount]) Is Null, 0.0m, [employee.BonusDetailsCollection][].Sum([amount])) + [employee.salary]")]
        public decimal? compensation
        {
            get { return (decimal?)(EvaluateAlias(nameof(compensation))); }
        }
    }

}
