//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class CompanionDetails : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Companion fCompanion;
        [Association(@"CompanionDetailsReferencesCompanion")]
        public Companion Companion
        {
            get { return fCompanion; }
            set { SetPropertyValue<Companion>(nameof(Companion), ref fCompanion, value); }
        }
        Admission fStay;
        [Association(@"CompanionDetailsReferencesAdmission")]
        public Admission Stay
        {
            get { return fStay; }
            set { SetPropertyValue<Admission>(nameof(Stay), ref fStay, value); }
        }
        DateTime fdate;
        [Indexed(@"Stay", Name = @"Index1", Unique = true)]
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
    }

}
