//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Companion : DevExpress.Persistent.BaseImpl.Person
    {
        string fID;

        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        [Association(@"CompanionDetailsReferencesCompanion")]
        public XPCollection<CompanionDetails> CompanionDetailsCollection { get { return GetCollection<CompanionDetails>(nameof(CompanionDetailsCollection)); } }
    }

}
