//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Conratct : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        double fOverAllDiscount;
        public double OverAllDiscount
        {
            get { return fOverAllDiscount; }
            set { SetPropertyValue<double>(nameof(OverAllDiscount), ref fOverAllDiscount, value); }
        }
        PriceList fPricList;
        public PriceList PricList
        {
            get { return fPricList; }
            set { SetPropertyValue<PriceList>(nameof(PricList), ref fPricList, value); }
        }
        [Association(@"ConractDepartmentReferencesConratct")]
        public XPCollection<ConractDepartment> ConractDepartments { get { return GetCollection<ConractDepartment>(nameof(ConractDepartments)); } }
        [Association(@"ConractServiceDiscountReferencesConratct")]
        public XPCollection<ConractServiceDiscount> ConractServiceDiscounts { get { return GetCollection<ConractServiceDiscount>(nameof(ConractServiceDiscounts)); } }
    }

}
