//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Discount : XPObject
    {
        int fID;
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        [PersistentAlias("LocalDateTimeToday()")]
        public DateTime Date
        {
            get { return (DateTime)(EvaluateAlias(nameof(Date))); }
        }
        decimal fPercentage;
        public decimal Percentage
        {
            get { return fPercentage; }
            set { SetPropertyValue<decimal>(nameof(Percentage), ref fPercentage, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"AppointmentReferencesDiscount")]
        public XPCollection<Appointment> Appointments { get { return GetCollection<Appointment>(nameof(Appointments)); } }
    }

}
