//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Employee : DevExpress.Persistent.BaseImpl.Person
    {
        string fNationalID;
        public string NationalID
        {
            get { return fNationalID; }
            set { SetPropertyValue<string>(nameof(NationalID), ref fNationalID, value); }
        }
        decimal fbaseSalary;
        public decimal baseSalary
        {
            get { return fbaseSalary; }
            set { SetPropertyValue<decimal>(nameof(baseSalary), ref fbaseSalary, value); }
        }
        int fdaysOfWork;
        public int daysOfWork
        {
            get { return fdaysOfWork; }
            set { SetPropertyValue<int>(nameof(daysOfWork), ref fdaysOfWork, value); }
        }
        int fhoursOfDay;
        public int hoursOfDay
        {
            get { return fhoursOfDay; }
            set { SetPropertyValue<int>(nameof(hoursOfDay), ref fhoursOfDay, value); }
        }
        Section fsection;
        public Section section
        {
            get { return fsection; }
            set { SetPropertyValue<Section>(nameof(section), ref fsection, value); }
        }
        Job fjob;
        public Job job
        {
            get { return fjob; }
            set { SetPropertyValue<Job>(nameof(job), ref fjob, value); }
        }
        decimal fhousing;
        public decimal housing
        {
            get { return fhousing; }
            set { SetPropertyValue<decimal>(nameof(housing), ref fhousing, value); }
        }
        decimal fincentive;
        public decimal incentive
        {
            get { return fincentive; }
            set { SetPropertyValue<decimal>(nameof(incentive), ref fincentive, value); }
        }
        decimal ftransportation;
        public decimal transportation
        {
            get { return ftransportation; }
            set { SetPropertyValue<decimal>(nameof(transportation), ref ftransportation, value); }
        }
        decimal fsocialInsurane;
        public decimal socialInsurane
        {
            get { return fsocialInsurane; }
            set { SetPropertyValue<decimal>(nameof(socialInsurane), ref fsocialInsurane, value); }
        }
        decimal fmedicine;
        public decimal medicine
        {
            get { return fmedicine; }
            set { SetPropertyValue<decimal>(nameof(medicine), ref fmedicine, value); }
        }
        decimal fothers;
        public decimal others
        {
            get { return fothers; }
            set { SetPropertyValue<decimal>(nameof(others), ref fothers, value); }
        }
        decimal finsuranceDeduction;
        public decimal insuranceDeduction
        {
            get { return finsuranceDeduction; }
            set { SetPropertyValue<decimal>(nameof(insuranceDeduction), ref finsuranceDeduction, value); }
        }
        decimal fotherDeductions;
        public decimal otherDeductions
        {
            get { return fotherDeductions; }
            set { SetPropertyValue<decimal>(nameof(otherDeductions), ref fotherDeductions, value); }
        }
        [Association(@"AbsenceDetailsReferencesEmployee")]
        public XPCollection<AbsenceDetails> AbsenceDetailsCollection { get { return GetCollection<AbsenceDetails>(nameof(AbsenceDetailsCollection)); } }
        [Association(@"VacationDetailsReferencesEmployee")]
        public XPCollection<VacationDetails> VacationDetailsCollection { get { return GetCollection<VacationDetails>(nameof(VacationDetailsCollection)); } }
        [Association(@"DeductionDetailsReferencesEmployee")]
        public XPCollection<DeductionDetails> DeductionDetailsCollection { get { return GetCollection<DeductionDetails>(nameof(DeductionDetailsCollection)); } }
        [Association(@"BonusDetailsReferencesEmployee")]
        public XPCollection<BonusDetails> BonusDetailsCollection { get { return GetCollection<BonusDetails>(nameof(BonusDetailsCollection)); } }
        [Association(@"CompensationReferencesEmployee")]
        public XPCollection<CompensationDetails> Compensations { get { return GetCollection<CompensationDetails>(nameof(Compensations)); } }
        [Association(@"WarningReferencesEmployee")]
        public XPCollection<Warning> Warnings { get { return GetCollection<Warning>(nameof(Warnings)); } }
        [Association(@"SalaryAdvanceReferencesEmployee")]
        public XPCollection<SalaryAdvance> SalaryAdvances { get { return GetCollection<SalaryAdvance>(nameof(SalaryAdvances)); } }
    }

}
