//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ICU : XPObject
    {
        string fBedID;
        public string BedID
        {
            get { return fBedID; }
            set { SetPropertyValue<string>(nameof(BedID), ref fBedID, value); }
        }
        bool fIsAvailable;
        public bool IsAvailable
        {
            get { return fIsAvailable; }
            set { SetPropertyValue<bool>(nameof(IsAvailable), ref fIsAvailable, value); }
        }
    }

}
