//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class InPatientSettings : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        double fServiceRate;
        public double ServiceRate
        {
            get { return fServiceRate; }
            set { SetPropertyValue<double>(nameof(ServiceRate), ref fServiceRate, value); }
        }
        decimal fStampPrice;
        public decimal StampPrice
        {
            get { return fStampPrice; }
            set { SetPropertyValue<decimal>(nameof(StampPrice), ref fStampPrice, value); }
        }
    }

}
