//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class JournalDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        JournalEntry fjournal;
        [Association(@"JournalDetailsReferencesJournalEntry")]
        public JournalEntry journal
        {
            get { return fjournal; }
            set { SetPropertyValue<JournalEntry>(nameof(journal), ref fjournal, value); }
        }
        Account faccount;
        public Account account
        {
            get { return faccount; }
            set { SetPropertyValue<Account>(nameof(account), ref faccount, value); }
        }
        decimal fcredit;
        public decimal credit
        {
            get { return fcredit; }
            set { SetPropertyValue<decimal>(nameof(credit), ref fcredit, value); }
        }
        decimal fdebit;
        public decimal debit
        {
            get { return fdebit; }
            set { SetPropertyValue<decimal>(nameof(debit), ref fdebit, value); }
        }
        string fstatement;
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
    }

}
