//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class JournalEntry : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        string fstatement;
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
        bool fpost;
        public bool post
        {
            get { return fpost; }
            set { SetPropertyValue<bool>(nameof(post), ref fpost, value); }
        }
        string ftype;
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>(nameof(type), ref ftype, value); }
        }
        string fobjectKey;
        public string objectKey
        {
            get { return fobjectKey; }
            set { SetPropertyValue<string>(nameof(objectKey), ref fobjectKey, value); }
        }
        [Association(@"JournalDetailsReferencesJournalEntry"), Aggregated]
        public XPCollection<JournalDetails> JournalDetailsCollection { get { return GetCollection<JournalDetails>(nameof(JournalDetailsCollection)); } }
    }

}
