//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class MasterAccount : XPBaseObject
    {
        int faccountNumber;
        [Key]
        public int accountNumber
        {
            get { return faccountNumber; }
            set { SetPropertyValue<int>(nameof(accountNumber), ref faccountNumber, value); }
        }
        string faccountName;
        public string accountName
        {
            get { return faccountName; }
            set { SetPropertyValue<string>(nameof(accountName), ref faccountName, value); }
        }
        decimal fcredit;
        public decimal credit
        {
            get { return fcredit; }
            set { SetPropertyValue<decimal>(nameof(credit), ref fcredit, value); }
        }
        decimal fdebit;
        public decimal debit
        {
            get { return fdebit; }
            set { SetPropertyValue<decimal>(nameof(debit), ref fdebit, value); }
        }
        [Association(@"SubAccountReferencesMasterAccount")]
        public XPCollection<SubAccount> SubAccounts { get { return GetCollection<SubAccount>(nameof(SubAccounts)); } }
    }

}
