//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Package : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        decimal fmedicineLimit;
        public decimal medicineLimit
        {
            get { return fmedicineLimit; }
            set { SetPropertyValue<decimal>(nameof(medicineLimit), ref fmedicineLimit, value); }
        }
        decimal fSuppliesLimit;
        public decimal SuppliesLimit
        {
            get { return fSuppliesLimit; }
            set { SetPropertyValue<decimal>(nameof(SuppliesLimit), ref fSuppliesLimit, value); }
        }
        decimal fTestsLimit;
        public decimal TestsLimit
        {
            get { return fTestsLimit; }
            set { SetPropertyValue<decimal>(nameof(TestsLimit), ref fTestsLimit, value); }
        }
        decimal fXrayLimit;
        public decimal XrayLimit
        {
            get { return fXrayLimit; }
            set { SetPropertyValue<decimal>(nameof(XrayLimit), ref fXrayLimit, value); }
        }
        decimal fEndoscopyLimit;
        public decimal EndoscopyLimit
        {
            get { return fEndoscopyLimit; }
            set { SetPropertyValue<decimal>(nameof(EndoscopyLimit), ref fEndoscopyLimit, value); }
        }
        decimal fServicesLimit;
        public decimal ServicesLimit
        {
            get { return fServicesLimit; }
            set { SetPropertyValue<decimal>(nameof(ServicesLimit), ref fServicesLimit, value); }
        }
        int fNumDaysnorm;
        public int NumDaysnorm
        {
            get { return fNumDaysnorm; }
            set { SetPropertyValue<int>(nameof(NumDaysnorm), ref fNumDaysnorm, value); }
        }
        int fNumDaysICU;
        public int NumDaysICU
        {
            get { return fNumDaysICU; }
            set { SetPropertyValue<int>(nameof(NumDaysICU), ref fNumDaysICU, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
    }

}
