//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.ExpressApp.DefaultListViewOptions(DevExpress.ExpressApp.MasterDetailMode.ListViewOnly, true, DevExpress.ExpressApp.NewItemRowPosition.Bottom)]
    public partial class PackageDetail : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Package fPackage;
        public Package Package
        {
            get { return fPackage; }
            set { SetPropertyValue<Package>(nameof(Package), ref fPackage, value); }
        }
        ReceptionDesk fReciption;
        [Association(@"PackageDetailReferencesReceptionDesk")]
        public ReceptionDesk Reciption
        {
            get { return fReciption; }
            set { SetPropertyValue<ReceptionDesk>(nameof(Reciption), ref fReciption, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        decimal fNormalRoomTotal;
        public decimal NormalRoomTotal
        {
            get { return fNormalRoomTotal; }
            set { SetPropertyValue<decimal>(nameof(NormalRoomTotal), ref fNormalRoomTotal, value); }
        }
        decimal fICuRoomTotal;
        public decimal ICuRoomTotal
        {
            get { return fICuRoomTotal; }
            set { SetPropertyValue<decimal>(nameof(ICuRoomTotal), ref fICuRoomTotal, value); }
        }
        bool fApplyed;
        [ColumnDefaultValue(false)]
        public bool Applyed
        {
            get { return fApplyed; }
            set { SetPropertyValue<bool>(nameof(Applyed), ref fApplyed, value); }
        }
    }

}
