//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Payments : XPBaseObject
    {
        int fpaymentID;
        [Key(true)]
        public int paymentID
        {
            get { return fpaymentID; }
            set { SetPropertyValue<int>(nameof(paymentID), ref fpaymentID, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        Patient fPatient;
        [Association(@"PaymentReferencesPatient")]
        public Patient Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<Patient>(nameof(Patient), ref fPatient, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        Safe fsafe;
        [Association(@"PaymentsReferencesSafe")]
        public Safe safe
        {
            get { return fsafe; }
            set { SetPropertyValue<Safe>(nameof(safe), ref fsafe, value); }
        }
        ReceptionDesk fReceptionDesk;
        [Association(@"PaymentsReferencesReceptionDesk")]
        public ReceptionDesk ReceptionDesk
        {
            get { return fReceptionDesk; }
            set { SetPropertyValue<ReceptionDesk>(nameof(ReceptionDesk), ref fReceptionDesk, value); }
        }
        Emergency fEmergency;
        [Association(@"PaymentsReferencesEmergency")]
        public Emergency Emergency
        {
            get { return fEmergency; }
            set { SetPropertyValue<Emergency>(nameof(Emergency), ref fEmergency, value); }
        }
        Appointment fAppointment;
        public Appointment Appointment
        {
            get { return fAppointment; }
            set { SetPropertyValue<Appointment>(nameof(Appointment), ref fAppointment, value); }
        }
        JournalEntry fjournalEntry;
        public JournalEntry journalEntry
        {
            get { return fjournalEntry; }
            set { SetPropertyValue<JournalEntry>(nameof(journalEntry), ref fjournalEntry, value); }
        }
    }

}
