//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.ExpressApp.DefaultListViewOptions(DevExpress.ExpressApp.MasterDetailMode.ListViewOnly, true, DevExpress.ExpressApp.NewItemRowPosition.Bottom)]
    public partial class PriceListDetail : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        PriceList fPriceList;
        [Association(@"PriceListDetailReferencesPriceList")]
        public PriceList PriceList
        {
            get { return fPriceList; }
            set { SetPropertyValue<PriceList>(nameof(PriceList), ref fPriceList, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        ServiceBase fServiceBase;
        [Association(@"PriceListDetailReferencesServiceBase")]
        public ServiceBase ServiceBase
        {
            get { return fServiceBase; }
            set { SetPropertyValue<ServiceBase>(nameof(ServiceBase), ref fServiceBase, value); }
        }
    }

}
