//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ProductRefund : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Admission fadmission;
        [Association(@"ProductRefundReferencesAdmission")]
        public Admission admission
        {
            get { return fadmission; }
            set { SetPropertyValue<Admission>(nameof(admission), ref fadmission, value); }
        }
        StayMedications fStayMediction;
        [DevExpress.Persistent.Base.DataSourceCriteria("Stay ='@this.admission'")]
        public StayMedications StayMediction
        {
            get { return fStayMediction; }
            set { SetPropertyValue<StayMedications>(nameof(StayMediction), ref fStayMediction, value); }
        }
        double fRefundQuantity;
        public double RefundQuantity
        {
            get { return fRefundQuantity; }
            set { SetPropertyValue<double>(nameof(RefundQuantity), ref fRefundQuantity, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        [PersistentAlias("Iif([price] * ToDecimal([RefundQuantity]) Is Null, 0.0m, [price] * ToDecimal([RefundQuantity]))")]
        public decimal Amount
        {
            get { return (decimal)(EvaluateAlias(nameof(Amount))); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
    }

}
