//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class PurchasingOrder : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Account fsupplierAccount;
        public Account supplierAccount
        {
            get { return fsupplierAccount; }
            set { SetPropertyValue<Account>(nameof(supplierAccount), ref fsupplierAccount, value); }
        }
        Account fpaymentAccount;
        public Account paymentAccount
        {
            get { return fpaymentAccount; }
            set { SetPropertyValue<Account>(nameof(paymentAccount), ref fpaymentAccount, value); }
        }
        JournalEntry fjournalEntry;
        public JournalEntry journalEntry
        {
            get { return fjournalEntry; }
            set { SetPropertyValue<JournalEntry>(nameof(journalEntry), ref fjournalEntry, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        Inventory finventory;
        [DevExpress.Persistent.Base.DataSourceCriteria("WearhouseType.Name =='أساسي'")]
        public Inventory inventory
        {
            get { return finventory; }
            set { SetPropertyValue<Inventory>(nameof(inventory), ref finventory, value); }
        }
        bool fisConfirmed;
        [ColumnDefaultValue(false)]
        public bool isConfirmed
        {
            get { return fisConfirmed; }
            set { SetPropertyValue<bool>(nameof(isConfirmed), ref fisConfirmed, value); }
        }
        string fstatement;
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
        decimal fpaid;
        public decimal paid
        {
            get { return fpaid; }
            set { SetPropertyValue<decimal>(nameof(paid), ref fpaid, value); }
        }
        int fdiscount;
        public int discount
        {
            get { return fdiscount; }
            set { SetPropertyValue<int>(nameof(discount), ref fdiscount, value); }
        }
        decimal fpurchasingServices;
        public decimal purchasingServices
        {
            get { return fpurchasingServices; }
            set { SetPropertyValue<decimal>(nameof(purchasingServices), ref fpurchasingServices, value); }
        }
        double fVAT;
        public double VAT
        {
            get { return fVAT; }
            set { SetPropertyValue<double>(nameof(VAT), ref fVAT, value); }
        }
        double ftax;
        public double tax
        {
            get { return ftax; }
            set { SetPropertyValue<double>(nameof(tax), ref ftax, value); }
        }
        decimal ftotalOrder;
        public decimal totalOrder
        {
            get { return ftotalOrder; }
            set { SetPropertyValue<decimal>(nameof(totalOrder), ref ftotalOrder, value); }
        }
        [Association(@"PurchasingOrderDetailReferencesPurchasingOrder"), Aggregated]
        public XPCollection<PurchasingOrderDetail> PurchasingOrderDetails { get { return GetCollection<PurchasingOrderDetail>(nameof(PurchasingOrderDetails)); } }
    }

}
