//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class PurchaseRequest : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        bool fApproved;
        public bool Approved
        {
            get { return fApproved; }
            set { SetPropertyValue<bool>(nameof(Approved), ref fApproved, value); }
        }
        PurchasingOrder fOrder;
        public PurchasingOrder Order
        {
            get { return fOrder; }
            set { SetPropertyValue<PurchasingOrder>(nameof(Order), ref fOrder, value); }
        }
        Inventory fWarehouse;
        [DevExpress.Persistent.Base.DataSourceCriteria("WearhouseType.Name =='أساسي'")]
        public Inventory Warehouse
        {
            get { return fWarehouse; }
            set { SetPropertyValue<Inventory>(nameof(Warehouse), ref fWarehouse, value); }
        }
        [Association(@"PurchaseRequestDetailReferencesPurchaseRequest")]
        public XPCollection<PurchaseRequestDetail> PurchaseRequestDetails { get { return GetCollection<PurchaseRequestDetail>(nameof(PurchaseRequestDetails)); } }
    }

}
