//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class receiptClientBond : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Account ffromAccount;
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public Account fromAccount
        {
            get { return ffromAccount; }
            set { SetPropertyValue<Account>(nameof(fromAccount), ref ffromAccount, value); }
        }
        Account fintoAccount;
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public Account intoAccount
        {
            get { return fintoAccount; }
            set { SetPropertyValue<Account>(nameof(intoAccount), ref fintoAccount, value); }
        }
        decimal ffromAccountBalance;
        public decimal fromAccountBalance
        {
            get { return ffromAccountBalance; }
            set { SetPropertyValue<decimal>(nameof(fromAccountBalance), ref ffromAccountBalance, value); }
        }
        decimal fintoAccountBalance;
        public decimal intoAccountBalance
        {
            get { return fintoAccountBalance; }
            set { SetPropertyValue<decimal>(nameof(intoAccountBalance), ref fintoAccountBalance, value); }
        }
        decimal famount;
        public decimal amount
        {
            get { return famount; }
            set { SetPropertyValue<decimal>(nameof(amount), ref famount, value); }
        }
        string fstatement;
        [Size(SizeAttribute.Unlimited)]
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        int fchequeNumber;
        public int chequeNumber
        {
            get { return fchequeNumber; }
            set { SetPropertyValue<int>(nameof(chequeNumber), ref fchequeNumber, value); }
        }
        DateTime fchequeDate;
        public DateTime chequeDate
        {
            get { return fchequeDate; }
            set { SetPropertyValue<DateTime>(nameof(chequeDate), ref fchequeDate, value); }
        }
        Bank fchequeBank;
        public Bank chequeBank
        {
            get { return fchequeBank; }
            set { SetPropertyValue<Bank>(nameof(chequeBank), ref fchequeBank, value); }
        }
        bool fpost;
        public bool post
        {
            get { return fpost; }
            set { SetPropertyValue<bool>(nameof(post), ref fpost, value); }
        }
        JournalEntry fjournal;
        public JournalEntry journal
        {
            get { return fjournal; }
            set { SetPropertyValue<JournalEntry>(nameof(journal), ref fjournal, value); }
        }
        string fCreatedBy;
        public string CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<string>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        string fUpdatedBy;
        public string UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<string>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
    }

}
