//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Room : DevExpress.Persistent.BaseImpl.BaseObject
    {
        int fnumber;
        public int number
        {
            get { return fnumber; }
            set { SetPropertyValue<int>(nameof(number), ref fnumber, value); }
        }
        decimal froomCost;
        public decimal roomCost
        {
            get { return froomCost; }
            set { SetPropertyValue<decimal>(nameof(roomCost), ref froomCost, value); }
        }
        decimal fsupervisionCost;
        public decimal supervisionCost
        {
            get { return fsupervisionCost; }
            set { SetPropertyValue<decimal>(nameof(supervisionCost), ref fsupervisionCost, value); }
        }
        decimal fcareCost;
        public decimal careCost
        {
            get { return fcareCost; }
            set { SetPropertyValue<decimal>(nameof(careCost), ref fcareCost, value); }
        }
        [Association(@"bedReferencesRoom"), Aggregated]
        public XPCollection<bed> beds { get { return GetCollection<bed>(nameof(beds)); } }
    }

}
