//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Safe : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        [PersistentAlias("[PaymentsCollection][].Sum([amount])")]
        public decimal totalPayments
        {
            get { return (decimal)(EvaluateAlias(nameof(totalPayments))); }
        }
        [PersistentAlias("[SpendingsCollection][].Sum([amount])")]
        public decimal totalSpendings
        {
            get { return (decimal)(EvaluateAlias(nameof(totalSpendings))); }
        }
        [Association(@"PaymentsReferencesSafe")]
        public XPCollection<Payments> PaymentsCollection { get { return GetCollection<Payments>(nameof(PaymentsCollection)); } }
        [Association(@"SpendingsReferencesSafe")]
        public XPCollection<Spendings> SpendingsCollection { get { return GetCollection<Spendings>(nameof(SpendingsCollection)); } }
    }

}
