//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.ExpressApp.DefaultListViewOptions(DevExpress.ExpressApp.MasterDetailMode.ListViewOnly, true, DevExpress.ExpressApp.NewItemRowPosition.Bottom)]
    public partial class SalaryPaymentDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Employee femployee;
        public Employee employee
        {
            get { return femployee; }
            set { SetPropertyValue<Employee>(nameof(employee), ref femployee, value); }
        }
        SalaryPayment fSalaryPayment;
        [Association(@"SalaryDetailsReferencesSalaryDocument")]
        public SalaryPayment SalaryPayment
        {
            get { return fSalaryPayment; }
            set { SetPropertyValue<SalaryPayment>(nameof(SalaryPayment), ref fSalaryPayment, value); }
        }
        decimal fbaseSalary;
        public decimal baseSalary
        {
            get { return fbaseSalary; }
            set { SetPropertyValue<decimal>(nameof(baseSalary), ref fbaseSalary, value); }
        }
        int fdaysOfWork;
        public int daysOfWork
        {
            get { return fdaysOfWork; }
            set { SetPropertyValue<int>(nameof(daysOfWork), ref fdaysOfWork, value); }
        }
        int fhoursOfWork;
        public int hoursOfWork
        {
            get { return fhoursOfWork; }
            set { SetPropertyValue<int>(nameof(hoursOfWork), ref fhoursOfWork, value); }
        }
        decimal fhousing;
        public decimal housing
        {
            get { return fhousing; }
            set { SetPropertyValue<decimal>(nameof(housing), ref fhousing, value); }
        }
        decimal fincentive;
        public decimal incentive
        {
            get { return fincentive; }
            set { SetPropertyValue<decimal>(nameof(incentive), ref fincentive, value); }
        }
        decimal ftransportation;
        public decimal transportation
        {
            get { return ftransportation; }
            set { SetPropertyValue<decimal>(nameof(transportation), ref ftransportation, value); }
        }
        decimal fsocialInsurane;
        public decimal socialInsurane
        {
            get { return fsocialInsurane; }
            set { SetPropertyValue<decimal>(nameof(socialInsurane), ref fsocialInsurane, value); }
        }
        decimal fmedicine;
        public decimal medicine
        {
            get { return fmedicine; }
            set { SetPropertyValue<decimal>(nameof(medicine), ref fmedicine, value); }
        }
        decimal fgrossPay;
        public decimal grossPay
        {
            get { return fgrossPay; }
            set { SetPropertyValue<decimal>(nameof(grossPay), ref fgrossPay, value); }
        }
        decimal fothers;
        public decimal others
        {
            get { return fothers; }
            set { SetPropertyValue<decimal>(nameof(others), ref fothers, value); }
        }
        decimal ftotalPenalties;
        public decimal totalPenalties
        {
            get { return ftotalPenalties; }
            set { SetPropertyValue<decimal>(nameof(totalPenalties), ref ftotalPenalties, value); }
        }
        decimal ftotalAdvances;
        public decimal totalAdvances
        {
            get { return ftotalAdvances; }
            set { SetPropertyValue<decimal>(nameof(totalAdvances), ref ftotalAdvances, value); }
        }
        decimal ftotalBonuses;
        public decimal totalBonuses
        {
            get { return ftotalBonuses; }
            set { SetPropertyValue<decimal>(nameof(totalBonuses), ref ftotalBonuses, value); }
        }
        decimal finsuranceDeduction;
        public decimal insuranceDeduction
        {
            get { return finsuranceDeduction; }
            set { SetPropertyValue<decimal>(nameof(insuranceDeduction), ref finsuranceDeduction, value); }
        }
        decimal fotherDeductions;
        public decimal otherDeductions
        {
            get { return fotherDeductions; }
            set { SetPropertyValue<decimal>(nameof(otherDeductions), ref fotherDeductions, value); }
        }
        decimal ftotalDeductions;
        public decimal totalDeductions
        {
            get { return ftotalDeductions; }
            set { SetPropertyValue<decimal>(nameof(totalDeductions), ref ftotalDeductions, value); }
        }
        decimal fnetPay;
        public decimal netPay
        {
            get { return fnetPay; }
            set { SetPropertyValue<decimal>(nameof(netPay), ref fnetPay, value); }
        }
        bool fpaySalary;
        public bool paySalary
        {
            get { return fpaySalary; }
            set { SetPropertyValue<bool>(nameof(paySalary), ref fpaySalary, value); }
        }
    }

}
