//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Service : XPBaseObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        decimal fPrice;
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        ServiceSecondCategory fcategory;
        [Association(@"ServiceReferencesServiceSecondCategory")]
        public ServiceSecondCategory category
        {
            get { return fcategory; }
            set { SetPropertyValue<ServiceSecondCategory>(nameof(category), ref fcategory, value); }
        }
        string fEnglishName;
        public string EnglishName
        {
            get { return fEnglishName; }
            set { SetPropertyValue<string>(nameof(EnglishName), ref fEnglishName, value); }
        }
    }

}
