//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class Service : ServiceBase
    {
        int fidentefcation;
        public int identefcation
        {
            get { return fidentefcation; }
            set { SetPropertyValue<int>(nameof(identefcation), ref fidentefcation, value); }
        }
        ServiceSecondCategory fcategory;
        [Association(@"ServiceReferencesServiceSecondCategory")]
        public ServiceSecondCategory category
        {
            get { return fcategory; }
            set { SetPropertyValue<ServiceSecondCategory>(nameof(category), ref fcategory, value); }
        }
        Clinc fClinic;
        public Clinc Clinic
        {
            get { return fClinic; }
            set { SetPropertyValue<Clinc>(nameof(Clinic), ref fClinic, value); }
        }
    }

}
