//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ServiceBase : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fLatinName;
        public string LatinName
        {
            get { return fLatinName; }
            set { SetPropertyValue<string>(nameof(LatinName), ref fLatinName, value); }
        }
        Department fDepartmet;
        public Department Departmet
        {
            get { return fDepartmet; }
            set { SetPropertyValue<Department>(nameof(Departmet), ref fDepartmet, value); }
        }
        [Association(@"PriceListDetailReferencesServiceBase")]
        public XPCollection<PriceListDetail> PriceListDetails { get { return GetCollection<PriceListDetail>(nameof(PriceListDetails)); } }
    }

}
