//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class ServiceSecondCategory : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fdescription;
        [Size(SizeAttribute.Unlimited)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        bool fbaseCategory;
        public bool baseCategory
        {
            get { return fbaseCategory; }
            set { SetPropertyValue<bool>(nameof(baseCategory), ref fbaseCategory, value); }
        }
        ServiceFirstCategory fserviceFirstCategory;
        [Association(@"ServiceSecondCategoryReferencesServiceFirstCategory")]
        public ServiceFirstCategory serviceFirstCategory
        {
            get { return fserviceFirstCategory; }
            set { SetPropertyValue<ServiceFirstCategory>(nameof(serviceFirstCategory), ref fserviceFirstCategory, value); }
        }
        [Association(@"ServiceReferencesServiceSecondCategory")]
        public XPCollection<Service> Services { get { return GetCollection<Service>(nameof(Services)); } }
    }

}
