//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class StartAccountsDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        StartAccounts fstartAccounts;
        [Association(@"StartAccountsDetailsReferencesStartAccounts")]
        public StartAccounts startAccounts
        {
            get { return fstartAccounts; }
            set { SetPropertyValue<StartAccounts>(nameof(startAccounts), ref fstartAccounts, value); }
        }
        string famount;
        public string amount
        {
            get { return famount; }
            set { SetPropertyValue<string>(nameof(amount), ref famount, value); }
        }
        Account faccount;
        public Account account
        {
            get { return faccount; }
            set { SetPropertyValue<Account>(nameof(account), ref faccount, value); }
        }
        string fstatement;
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
    }

}
