//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class StartAccounts : XPObject
    {
        string fID;
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>(nameof(ID), ref fID, value); }
        }
        string fdate;
        public string date
        {
            get { return fdate; }
            set { SetPropertyValue<string>(nameof(date), ref fdate, value); }
        }
        string fstatement;
        public string statement
        {
            get { return fstatement; }
            set { SetPropertyValue<string>(nameof(statement), ref fstatement, value); }
        }
        [Association(@"StartAccountsDetailsReferencesStartAccounts"), Aggregated]
        public XPCollection<StartAccountsDetails> StartAccountsDetailsCollection { get { return GetCollection<StartAccountsDetails>(nameof(StartAccountsDetailsCollection)); } }
    }

}
