//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class StockProduct : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Inventory fInventory;
        [Indexed(@"product", Name = @"Index1")]
        [Association(@"StockProductReferencesInventory")]
        public Inventory Inventory
        {
            get { return fInventory; }
            set { SetPropertyValue<Inventory>(nameof(Inventory), ref fInventory, value); }
        }
        Product fproduct;
        [Association(@"StockProductReferencesProduct")]
        public Product product
        {
            get { return fproduct; }
            set { SetPropertyValue<Product>(nameof(product), ref fproduct, value); }
        }
        double ffirstUnitQuantity;
        public double firstUnitQuantity
        {
            get { return ffirstUnitQuantity; }
            set { SetPropertyValue<double>(nameof(firstUnitQuantity), ref ffirstUnitQuantity, value); }
        }
        double fsecondUnitQuantity;
        public double secondUnitQuantity
        {
            get { return fsecondUnitQuantity; }
            set { SetPropertyValue<double>(nameof(secondUnitQuantity), ref fsecondUnitQuantity, value); }
        }
        double ftotalIn;
        public double totalIn
        {
            get { return ftotalIn; }
            set { SetPropertyValue<double>(nameof(totalIn), ref ftotalIn, value); }
        }
        double ftotalOut;
        public double totalOut
        {
            get { return ftotalOut; }
            set { SetPropertyValue<double>(nameof(totalOut), ref ftotalOut, value); }
        }
        [Association(@"StaySuppliesReferencesStockProduct"), Aggregated]
        public XPCollection<StaySupplies> StaySuppliesCollection { get { return GetCollection<StaySupplies>(nameof(StaySuppliesCollection)); } }
        [Association(@"TransferProductReferencesStockProduct"), Aggregated]
        public XPCollection<TransferProduct> TransferProducts { get { return GetCollection<TransferProduct>(nameof(TransferProducts)); } }
    }

}
