//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class StockTransfer : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Inventory fFromWarehouse;
        public Inventory FromWarehouse
        {
            get { return fFromWarehouse; }
            set { SetPropertyValue<Inventory>(nameof(FromWarehouse), ref fFromWarehouse, value); }
        }
        Inventory fToWearhouse;
        public Inventory ToWearhouse
        {
            get { return fToWearhouse; }
            set { SetPropertyValue<Inventory>(nameof(ToWearhouse), ref fToWearhouse, value); }
        }
        [Association(@"TransferProductReferencesStockTransfer")]
        public XPCollection<TransferProduct> TransferProducts { get { return GetCollection<TransferProduct>(nameof(TransferProducts)); } }
    }

}
