//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class SupervisionDetails : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        Employee fdoctor;
        [DevExpress.Persistent.Validation.RuleRequiredField]
		public Employee doctor
        {
            get { return fdoctor; }
            set { SetPropertyValue<Employee>(nameof(doctor), ref fdoctor, value); }
        }
        DateTime fdate;
        [DevExpress.Persistent.Validation.RuleRequiredField]
		public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        Admission fadmission;
        [Association(@"SupervisionDetailsReferencesAdmission")]
        public Admission admission
        {
            get { return fadmission; }
            set { SetPropertyValue<Admission>(nameof(admission), ref fadmission, value); }
        }
    }

}
