//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class Supplier : DevExpress.Persistent.BaseImpl.Person
    {
        string fnationalID;
        public string nationalID
        {
            get { return fnationalID; }
            set { SetPropertyValue<string>(nameof(nationalID), ref fnationalID, value); }
        }
        Account faccount;
        public Account account
        {
            get { return faccount; }
            set { SetPropertyValue<Account>(nameof(account), ref faccount, value); }
        }
        [PersistentAlias("[account.credit]")]
        public decimal credit
        {
            get { return (decimal)(EvaluateAlias(nameof(credit))); }
        }
        [PersistentAlias("[account.debit]")]
        public decimal debit
        {
            get { return (decimal)(EvaluateAlias(nameof(debit))); }
        }
        [Association(@"OrderExchangeReferencesSupplier")]
        public XPCollection<OrderExchange> OrderExchanges { get { return GetCollection<OrderExchange>(nameof(OrderExchanges)); } }
    }

}
