//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class SuppliesSettings : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        double fFromNotTo4;
        public double FromNotTo4
        {
            get { return fFromNotTo4; }
            set { SetPropertyValue<double>(nameof(FromNotTo4), ref fFromNotTo4, value); }
        }
        double fFrom5To9;
        public double From5To9
        {
            get { return fFrom5To9; }
            set { SetPropertyValue<double>(nameof(From5To9), ref fFrom5To9, value); }
        }
        double fFrom10To90;
        public double From10To90
        {
            get { return fFrom10To90; }
            set { SetPropertyValue<double>(nameof(From10To90), ref fFrom10To90, value); }
        }
        double fFrom91To149;
        public double From91To149
        {
            get { return fFrom91To149; }
            set { SetPropertyValue<double>(nameof(From91To149), ref fFrom91To149, value); }
        }
        double fFrom150ToAll;
        public double From150ToAll
        {
            get { return fFrom150ToAll; }
            set { SetPropertyValue<double>(nameof(From150ToAll), ref fFrom150ToAll, value); }
        }
    }

}
