//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class SuppliesSettings : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        double fFromNotTo5;
        public double FromNotTo5
        {
            get { return fFromNotTo5; }
            set { SetPropertyValue<double>(nameof(FromNotTo5), ref fFromNotTo5, value); }
        }
        double fFrom6To10;
        public double From6To10
        {
            get { return fFrom6To10; }
            set { SetPropertyValue<double>(nameof(From6To10), ref fFrom6To10, value); }
        }
        double fFrom11To20;
        public double From11To20
        {
            get { return fFrom11To20; }
            set { SetPropertyValue<double>(nameof(From11To20), ref fFrom11To20, value); }
        }
        double fFrom21To30;
        public double From21To30
        {
            get { return fFrom21To30; }
            set { SetPropertyValue<double>(nameof(From21To30), ref fFrom21To30, value); }
        }
        double fFrom31To40;
        public double From31To40
        {
            get { return fFrom31To40; }
            set { SetPropertyValue<double>(nameof(From31To40), ref fFrom31To40, value); }
        }
        double fFrom41To50;
        public double From41To50
        {
            get { return fFrom41To50; }
            set { SetPropertyValue<double>(nameof(From41To50), ref fFrom41To50, value); }
        }
        double fFrom50ToAll;
        public double From50ToAll
        {
            get { return fFrom50ToAll; }
            set { SetPropertyValue<double>(nameof(From50ToAll), ref fFrom50ToAll, value); }
        }
    }

}
