//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class SurgerySchedule : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Surgery fSurgery;
        public Surgery Surgery
        {
            get { return fSurgery; }
            set { SetPropertyValue<Surgery>(nameof(Surgery), ref fSurgery, value); }
        }
        DateTime fStart;
        [ColumnDefaultValue(2022, 9, 18, 0, 0, 0, 0)]
        public DateTime Start
        {
            get { return fStart; }
            set { SetPropertyValue<DateTime>(nameof(Start), ref fStart, value); }
        }
        DateTime fEnd;
        public DateTime End
        {
            get { return fEnd; }
            set { SetPropertyValue<DateTime>(nameof(End), ref fEnd, value); }
        }
        [PersistentAlias("Iif([Start] = null, LocalDateTimeNow(), GetDate([Start]))")]
        public DateTime StartDay
        {
            get { return (DateTime)(EvaluateAlias(nameof(StartDay))); }
        }
        surgeryRoom fRoom;
        [DevExpress.Persistent.Base.DataSourceCriteria(" isAvailable='true'")]
        public surgeryRoom Room
        {
            get { return fRoom; }
            set { SetPropertyValue<surgeryRoom>(nameof(Room), ref fRoom, value); }
        }
    }

}
