//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafDataModel.Module.BusinessObjects.test2
{

    public partial class TransferProduct : XPObject
    {
        StockProduct fStockProduct;
        public StockProduct StockProduct
        {
            get { return fStockProduct; }
            set { SetPropertyValue<StockProduct>(nameof(StockProduct), ref fStockProduct, value); }
        }
        ProductUnit fUnit;
        public ProductUnit Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<ProductUnit>(nameof(Unit), ref fUnit, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        double fCount;
        public double Count
        {
            get { return fCount; }
            set { SetPropertyValue<double>(nameof(Count), ref fCount, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        StockTransfer fStockTransfer;
        [Association(@"TransferProductReferencesStockTransfer")]
        public StockTransfer StockTransfer
        {
            get { return fStockTransfer; }
            set { SetPropertyValue<StockTransfer>(nameof(StockTransfer), ref fStockTransfer, value); }
        }
    }

}
