version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: docker-sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1434:1433"