//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ExpressApp {
            get {
                object obj = ResourceManager.GetObject("ExpressApp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;ar-EG&quot;&gt;
        ///  &lt;Title Text=&quot;Dashboard&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;ObjectDataSource Name=&quot;Object Data Source 1&quot; ComponentName=&quot;dashboardObjectDataSource1&quot;&gt;
        ///      &lt;DataSource Type=&quot;XafDataModel.Module.BusinessObjects.test2.Stay, HMS.Module, Version=1.0.7751.38835, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/ObjectDataSource&gt;
        ///    &lt;ObjectDataSource Name=&quot;Object Data Source 2&quot; ComponentName=&quot;dashboardObjectDataSource2&quot;&gt;
        ///      &lt;DataSource Type=&quot;XafData [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HospitalSections {
            get {
                return ResourceManager.GetString("HospitalSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;ar-EG&quot;&gt;
        ///  &lt;Title Text=&quot;Dashboard&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;ObjectDataSource Name=&quot;Object Data Source 1&quot; ComponentName=&quot;dashboardObjectDataSource1&quot;&gt;
        ///      &lt;DataSource Type=&quot;XafDataModel.Module.BusinessObjects.test2.Stay, HMS.Module, Version=1.0.7751.38364, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/ObjectDataSource&gt;
        ///    &lt;ObjectDataSource Name=&quot;Object Data Source 2&quot; ComponentName=&quot;dashboardObjectDataSource2&quot;&gt;
        ///      &lt;DataSource Type=&quot;XafData [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MainDashboard {
            get {
                return ResourceManager.GetString("MainDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;ar-EG&quot;&gt;
        ///  &lt;Title Text=&quot;لوحة المعلومات&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;مصدر بيانات SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;HMS&quot; ProviderKey=&quot;Access97&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;C:\Users\Saleem\Desktop\HMS.mdb&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///          &lt;Parameter Name=&quot;generateConnectionHelper&quot; Value=&quot;false&quot; /&gt;
        ///          &lt;Parameter Name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string paymentDashboard {
            get {
                return ResourceManager.GetString("paymentDashboard", resourceCulture);
            }
        }
    }
}
